# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    networks:
      - gateway-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - gateway-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

networks:
  gateway-network:
    driver: bridge

volumes:
  redis-data: